### PR TITLE
Add build script for doc site HTML files.

### PR DESCRIPTION
**Pull request by zackhall**
To run, use the npm script like such:

```
npm run doc:sitehtml
```

The script will generate a file at `doc/v4.XX.YY.html` which can be copied and added to the doc site.

### CODE REVIEW

**Comment by jdalton** [comment]
Could you rebase:
```bash
git fetch http://github.com/lodash/lodash
git reset --hard 39a65c8
git cherry-pick 958efba
git push origin +master
```

**Comment by zackhall** [comment]
Rebased! 🍻

**Comment by jdalton** [comment]
🌝

**Comment by demoneaux** [comment]
Cool. So for now we're still gonna use Docdown to generate the docs?

**Comment by jdalton** [comment]
Yep!

**Pull request merged**
