### PR TITLE
Fix code style error and doc nit

### PR DESCRIPTION
**Pull request by jfmengels**
Fix code style error introduced in 7811d59 and doc nit.

### CODE REVIEW

**Comment by jdalton** [comment]
Thank you!

**Comment by captbaritone** [comment]
Couldn't linting as part of Travis help catch this kind of error?

**Comment by jdalton** [comment]
I don't want to fail a test for linting. We should add it to the prepublish script though.

**Comment by jdalton** [comment]
@captbaritone Would you be open to creating a PR to add it add a prepublish npm script to run "npm run style" ?

**Comment by jfmengels** [comment]
Would it be possible to make Travis run the tests in the 7 different jobs as it is doing now, and add a new job that only runs the linting. That way, tests wouldn't break, but you could still see if there are linting errors.

**Comment by captbaritone** [comment]
Sure, I'll take a look.

**Pull request merged**
