### PR TITLE
Modify add() to parseFloat() variables passed

### PR DESCRIPTION
**Pull request by James-Dunn**
Now `_.add('6', '4');` will output 10 instead of 64.

### CODE REVIEW

**Comment by StreetStrider** [comment]
This case is just simple cast from string to number .This is a job for `Number` constructor, not `parseFloat`.

**Comment by James-Dunn** [comment]
Just depends on what behaviour is desired.

Number('') = 0;
Number(false) = 0;
Number('1foo') = NaN;

parseFloat('') = NaN;
parseFloat(false) = NaN;
parseFloat('1foo') = 1;

**Comment by StreetStrider** [comment]
@James-Dunn, yes, the difference is in cast — parse. This is cast.

**Comment by jdalton** [comment]
The `_.sum` behavior is to simply coerce values to a number `+value || 0`.

**Comment by jdalton** [comment]
@James-Dunn I'd be for coercing to a number but not `parseFloat`. Have you signed our [CLA](http://dojofoundation.org/about/claForm)?

**Comment by James-Dunn** [comment]
Changed it to Number() and signed CLA

**Pull request merged**
