### PR TITLE
[PR] Improve lodash.difference

### PR DESCRIPTION
**Pull request by zaclummys**
https://github.com/lodash/lodash/issues/3678

### CODE REVIEW

**Comment by jdalton** [comment]
Is this worth the cost?

**Comment by zaclummys** [comment]
I just wrote a simple benchmark to show it:

```js
const arr1 = Array(1e5);
const arr2 = Array(1e5);
```
> current diff arr1 arr2: 39.08477000892162ms
> current diff arr1 arr2: 39.205ms
> 
> current diff arr1 arr1: 29.104979991912842ms
> current diff arr1 arr1: 29.330ms
> 

> improved diff arr1 arr2: 17.764797002077103ms
> improved diff arr1 arr2: 17.969ms
> 
> improved diff arr1 arr1: 0.6249690055847168ms
> improved diff arr1 arr1: 0.840ms

**Comment by zaclummys** [comment]
@jdalton, I believe there's a significant improvement in performance. What's our next step?

**Comment by pedrofurtado** [comment]
@jdalton is this PR ready for merge, right? It's a great improvement in performance.

**Comment by jdalton** [comment]
It's an OK improvement in perf when you happen to have the same arrays and the arrays are large. I don't know about the other cases.

**Comment by zaclummys** [comment]
If this PR isn't OK, we can explore a way to improve it.
For example, we can add a pre-test: `values[0] === array && every(values, ...)`

**Comment by pedrofurtado** [comment]
@zaclummys I think to add this pre-test is good idea. As soon as possible, show here a brenchmark with different  arrays sizes. So,  we Will sure about how many improvement was made by different lengths of arrays.

**Comment by jdalton** [comment]
Thanks for you alls patience here. I'm going to hold off on this PR for now. If there's enough interest or a perf critical scenario arises where this can be applied then I'll totally revisit it.

**Pull request closed without merging**
