### PR TITLE
Add `afterBefore`

### PR DESCRIPTION
**Pull request by preethamvishy**
This method creates a function that invokes a function,  `func`, once it's called `start` or more times until it's called `end` times.

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @preethamvishy!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by preethamvishy** [comment]
Sounds good. 
Looking through the previous issues, I found #1384. This PR may be relevant.

**Comment by cope** [comment]
I _really_ have an issue with the name :D

Isn't afterBefore = now? 😵

**Comment by preethamvishy** [comment]
Haha probably. But I believe _afterBefore_ resonates more with the problem it's meant to solve than _now_.
Another strong contender could _between_? 
_after_ and _before_ are well know utilities and I like how lodash utilities are named after exactly what they do and I thought _afterBefore_ would be easy to discover.
 
Open to name changes if it gains traction and can be merged.

**Comment by StreetStrider** [comment]
> I like how lodash utilities are named after exactly what they do

That's not always so. Like, this name is ambiguous. I can't point out is `afterBefore` time-related, call count -related or numeric. It refers to some ordered values, though, but it hasn't enough cerainty.

`between` got strong resemblance  with numeric ranges.

**Comment by preethamvishy** [comment]
Can the same case of ambiguity relating time, call count, numeric etc be applied up for `after` and `before`? Both are popular utilities and I was banking on the popularity of both. I'm definitely open to the community's suggestions for naming if this PR is to be taken forward.

**Comment by StreetStrider** [comment]
@preethamvishy I think `before`  and `after` suffers from the same ambgiguity as other simple names because of LoDash (and previously, underscore) have got single namespace.

**Pull request closed without merging**
