### PR TITLE
Add _.startCase

### PR DESCRIPTION
**Pull request by thejameskyle**
```js
_.startCase('Foo Bar');
// => 'Foo Bar'

_.startCase('fooBar');
// => 'Foo Bar'

_.startCase('__foo_bar__');
// => 'Foo Bar'

_.startCase('FOO BAR');
// => 'FOO BAR'
```

Edit: Renamed from `titleCase` to `startCase`

### CODE REVIEW

**Comment by thejameskyle** [comment]
I'll clean up the tests later

**Comment by jdalton** [comment]
What you've implemented isn't title case but start case. I'd dig a `startCase` though I'm not so hot on the name. Is there an alternative name to start case?

**Comment by thejameskyle** [comment]
That was the name I was looking for! I named it title case because it was the closest I could come up with.

**Comment by thejameskyle** [comment]
[This](http://caseconverter.com/) website defines it as "proper case", but it looks like most people call that title case.

**Comment by jdalton** [comment]
It's a shame `capitalCase` is an alias of `titleCase` as that would be perfect. The `titleCase` carries with it lots of exceptions and isn't clearly defined.

**Comment by jdalton** [comment]
Let's go with the defined `startCase`. If you finish up the tests and docs I'll merge.

**Comment by thejameskyle** [comment]
I'll update this to `startCase`, but what are your thoughts on the ALL CAPS case?

```js
_.startCase('FOO BAR');
// > FOO BAR
// or
// > Foo Bar
```

**Comment by jdalton** [comment]
Have you signed [our CLA](http://dojofoundation.org/about/claForm)? I thought you have but can't find your entry.

**Comment by jdalton** [comment]
> I'll update this to startCase, but what are your thoughts on the ALL CAPS case?

Let's keep it simple. Title case just capitalizes each word. Nothing too fancy.

**Comment by jdalton** [comment]
Erm lol, *startCase

**Comment by thejameskyle** [comment]
@jdalton Is it in there as "James Rossini" or my email me[at]thejameskyle.com?

**Comment by jdalton** [comment]
Neither.

**Comment by thejameskyle** [comment]
Signed. I can never remember which projects I've actually done that for.

**Comment by jdalton** [comment]
Rock!

**Comment by thejameskyle** [comment]
Updated

**Pull request merged**
