### PR TITLE
Use baseGetTag instead of getTag where possible

### PR DESCRIPTION
**Pull request by blikblum**
Use baseGetTag instead of getTag where the fallbacks done in getTag are not relevant

This reduces the affected modules size significantly

### CODE REVIEW

**Comment by blikblum** [comment]
> Thanks @blikblum! (I really appreciate you taking the time to do these PRs).

You're welcome

> 
> 
> As a follow-up we need to remove the `masked` check workarounds from `baseGetTag` as it's causing potential ECMA262 pain for trying to normalize some things.

Can you elaborate more?

I investigated the possibility of removing masked workaround but it supports the case where toStringTag is mutated in an object:

```
const obj = {}
obj[Symbol.toStringTag] = 'test'
toString.call(obj) // -> [object test] instead of [object Object]
```

Complete test at https://codepen.io/blikblum/pen/NePaog

**Comment by jdalton** [comment]
The `baseGetTag` module can be simplified to just:

```js
 function baseGetTag(value) { 
   if (value == null) { 
     return value === undefined ? '[object Undefined]' : '[object Null]' 
   } 
   return toString.call(value) 
 }
```

**Comment by blikblum** [comment]
> The `baseGetTag` module can be simplified to just:

I can do that. But how about the case i mentioned above? 

A warn in documentation about the danger of mutating Symbol.toStringTag would be enough?

**Comment by jdalton** [comment]
I'm fine with it being left untackled. In this case if someone is really wanting their value to be branded as a given type then they want it to be treated as such. A note wouldn't hurt though.

**Pull request merged**
