### PR TITLE
does not pass the initial arguments along with the flow

### PR DESCRIPTION
**Pull request by theguriev**
Hey 😇
```js
// Now this example will not work because arguments not passing along the flow
const addOne = (num) => num + 1
const isDuplicate  = (current, index, array) => array.includes(current) // Array is undefined which is unlogical
const allFuncs = flow(addOne, isDuplicate)
[1, 2, 3].map(allFuncs)
```

Please review this.
Thank you! 😇

### CODE REVIEW

**Comment by gcofficial** [comment]
@Chantouch Can u review that, please? It would be cool to have it inside the lodash because now I'm using my own solution.

**Comment by Chantouch** [comment]
> @Chantouch Can u review that, please? It would be cool to have it inside the lodash because now I'm using my own solution.

@gcofficial why me ?  lol

**Comment by gcofficial** [comment]
> > @Chantouch Can u review that, please? It would be cool to have it inside the lodash because now I'm using my own solution.
> 
> @gcofficial why me ? lol

 Sorry, I thought that you should review that. 😇  Do you know who it should be? 
Who can review it and merge?

**Comment by Chantouch** [comment]
> > > @Chantouch Can u review that, please? It would be cool to have it inside the lodash because now I'm using my own solution.
> > 
> > 
> > @gcofficial why me ? lol
> 
> Sorry, I thought that you should review that. 😇 Do you know who it should be?
> Who can review it and merge?

Hmmm, just the owner of repo or who have authorized to review and merge .

**Comment by gcofficial** [comment]
@Chantouch Thx man. And sorry. I thought you have that. 

@jdalton Can u review that plz?

**Comment by gcofficial** [comment]
@bnjmnt4n Maybe u can review it and merge?

**Pull request closed without merging**
