### PR TITLE
Implement `filterMap()`

### PR DESCRIPTION
**Pull request by ndrewtl**
This implements the feature requested in #5300. Please let me know if you have any questions or comments

### CODE REVIEW

**Comment by camsteffen** [comment]
I think it should filter using [`isNil`](https://lodash.com/docs/4.17.15#isNil).

**Comment by ndrewtl** [comment]
@camsteffen the intention here is to have `null` be the one intended 'filter' value and only check for that, because other falsy values, such as `''`, `0`, etc. can be returned intentionally. In my opinion, a `null` signifies an intended non-value, which is a signal to the function to filter, while an `undefined` signifies that a value is missing, which is a valid return type. Furthermore for the Typescript typing, I would prefer to type the filtermap function as `(val: T) => U | null`, in which there is one clear return type that signals it should be filtered out, rather than the ugly `(val: T) => U | null | undefined`, which does not specify to the user if their filtering function should return `null` or `undefined`. Please let me know what you think and I'd like to get this merged.

**Comment by camsteffen** [comment]
`isNil` does not return true for all falsey values, just `null` and `undefined`. I agree with your description of `null` and `undefined`, but I still think `filterMap` should filter both out just because it would be the [least surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) behavior IMO.

**Comment by ndrewtl** [comment]
That's fair. Changed the PR to use `isNil`. Can you review @camsteffen ?

**Comment by camsteffen** [comment]
I'm not a maintainer.

**Comment by ndrewtl** [comment]
Hmm okay. Do you know who I can page then?

**Comment by ndrewtl** [comment]
Hi @jdalton could you review and merge this? This is a function I've wanted to use from lodash for quite awhile, and it would be fantastic if I could get it in.

**Pull request closed without merging**
