### PR TITLE
Add _.flip bitmask value to `createWrapper` documentation

### PR DESCRIPTION
**Pull request by iblamefish**

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @iblamefish!

Though not needed for this kind of PR, have you signed [our CLA](https://contribute.jquery.org/CLA/)?

**Comment by iblamefish** [comment]
@jdalton I have now! :)

**Comment by jdalton** [comment]
Thank you!

**Comment by dmethvin** [comment]
@jdalton so does this mean everything is cool with the license checker?

**Comment by jdalton** [comment]
No. It didn't kick-in. I had to manually check.

**Pull request merged**
