### PR TITLE
adding a regex pattern example

### PR DESCRIPTION
**Pull request by cope**
adding a regex pattern example to the documentation, stolen from https://stackoverflow.com/a/36429733/271873

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @cope!

This `String#replace` proxy method is being dropped in v5 so I don't want to spend time tweaking it now.

**Comment by rafaelss95** [comment]
@jdalton not really related to this PR, but os there any place that I can fins some more info about v5? The deprecations, remotions, added... progress?

**Comment by jdalton** [comment]
Hi @rafaelss95!

Part of v5 is covered in our [roadmap](https://github.com/lodash/lodash/wiki/Roadmap).
I'm currently finishing up the [esm loader](https://github.com/standard-things/esm) that Lodash v5 will rely on *(check out [its repo activity](https://github.com/standard-things/esm/graphs/contributors) :yum:)*

**Comment by rafaelss95** [comment]
Thanks for the info :)

**Pull request closed without merging**
