### PR TITLE
Support deepPaths as keynames for zipObject

### LINKED ISSUE #1151: deep path support for zipObject
The deep path support in 3.7.0 is exciting! After updating, my first use case was for zipping an array into an object, where some of the property names use bracket/subscript notation. (More specifically, my use case is a quick one-liner to parse a query string into an object.)

```js
_([
  [ "a[b]", 1 ],
  [ "a.c", 2 ]
]).object().value() //=>  { a: { b:1, c:2 } }
```
There are a couple of questions as to how this would be handled for `zipObject`.

Clearly when zipping objects, the deep path parsing would need to be optional. But we also have a number of different sub-features:

1. handling subscript notation with string key: `"a[b]"`
2. handling dot notation: `"a.b"`
3. handling empty subscript (to result in an array property): `"b[]"`
4. handling explicit numerical subscript: (result in array? or object? object with string keys or numbers?): `"b[0]"`

And there's the interplay with `_.pairs` to think about, as well.

### PR DESCRIPTION
**Pull request by jasonkarns**
Closes #1151

This is implemented by simply using baseSet within the body of zipObject
when building up the object

### CODE REVIEW

**Comment by jdalton** [comment]
Hey @jasonkarns! Have you signed [our CLA](http://dojofoundation.org/about/claForm)?

**Comment by jasonkarns** [comment]
signed

**Comment by jdalton** [comment]
:tada:

**Comment by jasonkarns** [comment]
It's worth mentioning that with this feature, lodash can reify an object from a querystring in a one-liner. (For common querystring structures, anyway. The array syntax can't use repeated-keys or the empty bracket form.)

**Comment by jdalton** [comment]
Neat!

**Comment by aliak00** [comment]
Hi, this behaviour breaks a few situations where a dot is part of your key, unexpected results ensue. Is that intentional to have that kind of behaviour or an oversight ... or maybe just preferred?

Case I actually have is mapping files in a directory to their fs.Stats object. File names can have dots, and boom.

Any recommended work around?

**Comment by jdalton** [comment]
This is resolved in the edge master branch with _.zipObjectDeep.

**Pull request merged**
