### PR TITLE
fix FP rearg for zipWith and inRange

### PR DESCRIPTION
**Pull request by billyjanitsch**
[2, 0, 1] seems like the more sensible default to me (there are 3 fewer exceptions, including the 2 this PR fixes) but I can revert this if you'd prefer.

### CODE REVIEW

**Comment by jdalton** [comment]
Oops you caught resolving a merge. Can you rebase this.

**Comment by billyjanitsch** [comment]
Done

**Comment by jdalton** [comment]
>  including the 2 this PR fixes

which 2?

**Comment by billyjanitsch** [comment]
`zipWith` and `inRange`, in the PR title

**Comment by jdalton** [comment]
Ah, I see they get it by switching the default, I looking them explicitly in the code.

**Comment by jdalton** [comment]
Looks good.

**Comment by billyjanitsch** [comment]
Thanks. 80c64da6567ba660bbd7aed4b4201964b960067c is sweet btw

**Pull request merged**
