### PR TITLE
Move lodash.com to gh-pages

### PR DESCRIPTION
**Pull request by InstyleVII**
I've made the changes necessary to setup gh-pages. Will need to do some work for the domain to point towards it but other than that the leg work is done. Also moved to remote-hosting github buttons and cleaned up a little bit of the code.

### CODE REVIEW

**Comment by jdalton** [comment]
Related to #815.

**Comment by jdalton** [comment]
Hi @InstyleVII! Could you squash these down to a single commit.

**Comment by phated** [comment]
Instead of having this in the main repo, I think we should create a repo named lodash.github.io as github suggests at https://pages.github.com

**Comment by jdalton** [comment]
I can dig that. Sorry @InstyleVII, lets move it [over there](https://github.com/lodash/lodash.github.io).

**Pull request closed without merging**
