### PR TITLE
Create fromEntries.js

### PR DESCRIPTION
**Pull request by ycmjason**
this acts as an alias for `_.fromPairs` since entries seem to be the official name for those pairs. (`Object.entries`)

### CODE REVIEW

**Comment by jdalton** [comment]
For v5 we'll likely just rename it to the official name. If you'd like to modify the PR to do that, that would be rad.

**Comment by ycmjason** [comment]
@jdalton should I keep `_.fromPairs` as an alias?

**Comment by jdalton** [comment]
You can drop `fromPairs`.

**Comment by jdalton** [comment]
Thanks @ycmjason!

**Pull request merged**
