### PR TITLE
Fix/fix merge

### PR DESCRIPTION
**Pull request by sinaabadi**
Fix inconsistent merging of multiple sources to function property
#3752

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @sinaabadi!

Will the GitHub UI let you retarget this PR to the `4.17.10` tag?

**Comment by sinaabadi** [comment]
Hey @jdalton, 
No :( I think I must recreate the pull request

**Comment by jdalton** [comment]
Okay!

**Comment by sinaabadi** [comment]
@jdalton create a new one?

**Comment by jdalton** [comment]
Yep. Let's see if that fixes it.

**Comment by sinaabadi** [comment]
@jdalton I can't target my pull request to a `4.17.10` tag.

**Comment by jdalton** [comment]
Merged https://github.com/lodash/lodash/commit/79b9d20a912118bf06acd093071902ed972daf4e.

**Pull request closed without merging**
