### PR TITLE
Update _.slice() docs

### PR DESCRIPTION
**Pull request by jareware**
Add a small note regarding negative start positions working as they do in Array.slice().

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @jareware!

I think this can be handled by modifying the doc note:
```
     * **Note:** This method is used instead of [`Array#slice`](https://mdn.io/Array/slice)
     * to ensure dense arrays are returned.
```

To say that this method is based on  [`Array#slice`](https://mdn.io/Array/slice) but used instead...

**Comment by jdalton** [comment]
@jareware would you mind updating the PR?

**Comment by jareware** [comment]
Is that better? Or should I drop the negative-index-mention altogether?

**Comment by jdalton** [comment]
You can drop the negative index as it's covered by the `Array#indexOf` link.

**Comment by jdalton** [comment]
Thanks!

**Pull request merged**
