### PR TITLE
add test for debounce 0

### PR DESCRIPTION
**Pull request by b3nj4m**
related to https://github.com/lodash/lodash/issues/2249

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @b3nj4m! Have you signed [our CLA](https://contribute.jquery.org/CLA/)?

**Comment by b3nj4m** [comment]
Not yet, I can do that.

**Comment by b3nj4m** [comment]
Signed.

**Comment by jdalton** [comment]
Thanks!

**Pull request merged**
