### PR TITLE
Add jsDelivr hits badge

### PR DESCRIPTION
**Pull request by LukasDrgon**
Hey, I noticed that lodash is the 5th most popular project on jsDelivr (congrats! :tada:), so I thought you might like this badge.

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @LukasDrgon!

I'm usually against badges but this is 👌 !

**Comment by jdalton** [comment]
Thank you!

**Comment by jdalton** [comment]
@LukasDrgon where did you see the top 5 rank btw?

**Comment by jdalton** [comment]
Oh I see, on the bottom [of the landing page](https://www.jsdelivr.com/)

**Comment by LukasDrgon** [comment]
Also at the bottom of https://www.jsdelivr.com/package/npm/lodash although it actually says 6th right now

**Comment by jdalton** [comment]
Ah thanks! It could be a rolling average.

**Pull request merged**
