### PR TITLE
add uniq Map for generated ID

### PR DESCRIPTION
**Pull request by PxyUp**
Good day, to the best of our knowledge, a unique element must have context. Let's say each person is unique, they can be numbered, like cats, dogs and the like

```
uniqueId("cat") // "cat1"
uniqueId("cat") // "cat2"
uniqueId("dog") // "dog1"
uniqueId("dog") // "dog2"
uniqueId() // "1"
uniqueId() // "2"
```

### CODE REVIEW

**Comment by jdalton** [comment]
I like this @PxyUp!

Thank you!

**Comment by StreetStrider** [comment]
That's awesome, but where's the test? @PxyUp

**Comment by jdalton** [comment]
The test debt will need to be paid soon. I'm wrapping up `@std/esm` v1 so that means I'll be able to focus more on Lodash v5.

**Comment by falsyvalues** [comment]
I think we should alter also description .

**Comment by omeid** [comment]
Why does it matter for the `uniqueId` to be serial?

**Comment by PxyUp** [comment]
@omeid because uniq id, can be only in context

**Comment by falsyvalues** [comment]
@omeid @PxyUp Worth to mention that this is the cheapest implementation that guarantee unique id in context.

**Pull request merged**
