### PR TITLE
perfomance fixes, eslint fixes

### PR DESCRIPTION
**Pull request by anatoliy8493**

### CODE REVIEW

**Comment by falsyvalues** [comment]
Hi @anatoliy8493!
Thank you, we are fine with current solution.

**Comment by jdalton** [comment]
Thank you @falsyvalues!

Ya know, after all these years I think it's time we go `===` :p
It's easy for new contributors to reason about.

**Comment by falsyvalues** [comment]
@jdalton Sure thing 👍

**Comment by jdalton** [comment]
🙃

**Comment by anatoliy8493** [comment]
@falsyvalues Hi! It might seem like a strong word, however if we use === instead of == we no need to JS Type Conversion

**Comment by jdalton** [comment]
In this case our usage of `==` was when there was no type conversion so basically spec'd identical steps as `===`. There is no noticeable performance difference with it.

**Pull request merged**
