### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wezzy**
in the documentation _.eq(object, other); return true and not false as expected

### CODE REVIEW

**Comment by jdalton** [comment]
Please update the source file and not the generated doc file.

**Comment by jdalton** [comment]
The example is correct. In v4 the `_.eq` method is for [`SameValueZero`](http://ecma-international.org/ecma-262/6.0/#sec-samevaluezero) comparisons. In v4 it was an alias for `_.isEqual`.

**Comment by wezzy** [comment]
Ops my bad thanks for the clarification I'm still using V3

**Comment by jdalton** [comment]
No worries. I've updated the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400) with a note on this.

**Pull request closed without merging**
