### PR TITLE
Implement `defaultToAny` method

### PR DESCRIPTION
**Pull request by eran-nussbaum**

### CODE REVIEW

**Comment by ypconstante** [comment]
How about adding a coalesce alias?

**Comment by StreetStrider** [comment]
@ypconstante `coalesce` is a name that spinning in my mind from point when I saw that ticket.

**Comment by eran-nussbaum** [comment]
@ypconstante @ypconstante I totally agree to that name.
I added it as an alias. Do I need to do anything other than add an `@alias` in JSDoc?...

Do you think I should just rename `defaultToAny` to `coalesce` instead?
I think that having its name start with `defaultTo` is good since it is closely-related to `defaultTo` method and its name should imply it.

**Comment by StreetStrider** [comment]
@eran-nussbaum I personally prefer one-word, concise and pretty names.

**Comment by eran-nussbaum** [comment]
@jdalton what's your take?

**Comment by jdalton** [comment]
I not a fan of aliases and I like how discoverable `defaultToAny` is.

**Comment by eran-nussbaum** [comment]
Okay.
So, do I need to do any further change to this PR? Is my implementation okay?…

**Comment by jdalton** [comment]
You need to remove the `@alias` meta data, you could also use the built-in `array.reduce` if you wanted.

**Comment by falsyvalues** [comment]
`defaultToAny` says nothing without checking what is behind in opposite to `coalesce` which is well known for this kind of operations.

**Comment by ypconstante** [comment]
Maybe it would be better if `defaultTo` accepted multiple values instead of having `defaultTo` and `defaultToAny`

**Comment by eran-nussbaum** [comment]
@jdalton do I need to do any more work on this PR for you to accept (and merge) it?

**Comment by jdalton** [comment]
Hi @eran-nussbaum!

Nope, things are good!

**Pull request merged**
