### PR TITLE
Implement optional descending order sort in #414

### PR DESCRIPTION
**Pull request by octref**
As per #414 .

The only thing I'm not sure is the jsdoc. I wrote this signature for `_.sortByAll` 's `props`:

```
     * @param {...(string|string[]|Object[])} props
```
But technically, it should be an mixed array, where element can be an Object or string.
Should I change it to this?
```
     * @param {...(string|(string|Object)[])} props
```

### CODE REVIEW

**Comment by jdalton** [comment]
> But technically, it should be an mixed array, where element can be an Object or string.
Should I change it to this?

Yah.

Can you cleanup the commits a bit. Also have you signed our [CLA](http://dojofoundation.org/about/claForm)?

**Comment by octref** [comment]
I signed the CLA with the username octref.

I'll clean up the jsdoc. Anything else to change?

**Comment by jdalton** [comment]
Ya the commits are a bit messy, it has a merge and an unrelated commit in there.

**Comment by octref** [comment]
Done. I wanted to do a rebase on lodash/master but somehow got it wrong. Now it should be good.

**Comment by jdalton** [comment]
I think this PR needs to more time to bake before including. There are several failing unit tests.
Also I'm still on the fence on the way to specify descending order. I'm thinking something like this is the least invasive.

```js
_.sortByAll(users, ['user', true, 'age', 'active', false]);
```

If the value after a key is a boolean it's used as the `desc` option for the preceding key.

**Comment by octref** [comment]
Sure, take your time. I understand not many (are there any?) methods in lodash take option objects like this & you want to keep it consistent.

However I don't see any failing unit tests when running from cli `node test/test.js`. What tests are you referring to?

I just came up with an idea, how about making a function like this:

```
_.sortByOrder(users, ['user', 'age'], [true, false])
```
so that we could keep both `sortByAll` and `sortByOrder` simple.

**Comment by jdalton** [comment]
> However I don't see any failing unit tests when running from cli node test/test.js. What tests are you referring to?

The travis-ci run indicator says it's failing:
https://travis-ci.org/lodash/lodash/builds/52379253

> I just came up with an idea, how about making a function like this:
```
_.sortByOrder(users, ['user', 'age'], [true, false])
```

So much nicer!

**Comment by octref** [comment]
The problem it's failing, i think, is I renamed `compareMultipleAscending` to `compareMultiple`. I made this change since the new one accept a third argument, 
```
  function compareMultiple(object, other, orderArray) {
```
which can be used to specify sorting order, and default to ascending.

On Travis it's using lodash-cli to build it, and since it has
```
'sortByAll': ['baseEach', 'baseFlatten', 'baseSortBy', 'compareMultipleAscending', 'isIterateeCall', 'isLength'],
```
It builds the wrong functions and fails the tests.

--

Should I leave `compareMultipleAscending` as it is and create a new one, `compareMultiple`, or remove the `compareMultipleAscending` completely? 

- Only `sortByAll` depends on `compareMultipleAscending`
- In my version, `compareMultiple(object, other)` behaves exactly as `compareMultipleAscending(object, other)` used to be.

And for `sortByOrder`, my plan is:

```
// Sort by `user` ascendingly
_.sortByOrder(users, 'user')
_.sortByOrder(users, 'user', true)

// Sort by `user` descendingly
_.sortByOrder(users, 'user', false)
_.sortByOrder(users, ['user'], [false])

// `props` and `orders` not same length
_.sortByOrder(users, ['user', 'age'], [false]) // Sort by `user` descendingly but `age` ascendingly
_.sortByOrder(users, ['user'], [false, false]) // Second `false` in `orders` ignored.
```

What do you think? Anything to be careful about?

**Comment by jdalton** [comment]
> The problem it's failing, i think, is I renamed compareMultipleAscending to compareMultiple. I made this change since the new one accept a third argument,

Naw the build is forgiving enough to leave unknown functions alone. No worries.

> Should I leave compareMultipleAscending as it is and create a new one, compareMultiple, or remove the compareMultipleAscending completely?

Create a new `compareMultiple`. Once we kick the implementation around we can remove or merge functionality as needed.

> And for sortByOrder, my plan is:

Looks good.

**Comment by d10** [comment]
Major :+1:! Thanks for the awesome work, @octref!

**Comment by octref** [comment]
@d10 
Nothing compared to what you guys are doing, but thanks!

The last commit get `sortByAll` and `compareMultipleAscending` back while adding `sortByOrder` and `compareMultiple`. Let me know if I did something wrong.

**Comment by jdalton** [comment]
Merged! Woo!

**Comment by octref** [comment]
Thanks I'll keep lurking around and see if I can help on anything :-)

**Comment by ItsLeeOwen** [comment]
What did you end up implementing for sort order?  When I attempt to use what looks like the latest syntax the sort does not produce expected results.  

_.sortByAll(users, ["user", "age"], [true, true])

If I look at what baseSortByOrder is being passed for "props" and "order" I see:
baseSortByOrder: ["user", "age", true, true] []

**Comment by ItsLeeOwen** [comment]
It's difficult to distinguish the intention of this line in sortByAll "baseSortByOrder(collection, baseFlatten(args, false, false, 1), [])" but changing the last two arguments to arg[1], arg[2] at least has it working on my end.  Although it does seem that desc true is actually asc.

The double array syntax is a bummer, but we have _.pluck

var sortBy = [
{key: 'user', desc: true},
{key: 'age', desc: false}
]
var sorted = _.sortByAll(input, _.pluck(sortBy, 'key'), _.pluck(sortBy, 'desc'))

**Comment by octref** [comment]
@ItsLeeOwen 
We end up doing it this way:
- `sortByAll` unchanged.
- Add `sortByOrder` which behaves this way:
```
// Sort 'user' descendingly but 'age' ascendingly
_.sortByOrder(users, ['user', 'age'], [false, true])
```
The signature is `_.sortByOrder(collection, props, orders)`. Sort for each prop ascendingly by default / when its corresponding value in `orders` is true, otherwise descendingly.

`baseSortByOrder` should be a private method and not accessible from outside.

**Comment by ItsLeeOwen** [comment]
@octref   Thanks, is commit 25b36703d068211302817b780d7119c3aed20de8 passing your tests for a sort of:_.sortByOrder(users, ['user', 'age'], [false, true])?

**Comment by octref** [comment]
@ItsLeeOwen 
Yes. At least Travis says so.
And 25b3670 is another problem about `_.defaults` not working properly when called by `_.reduce` or `_.reduceRight`. You can see the details here.
https://github.com/lodash/lodash/pull/1014

**Comment by ItsLeeOwen** [comment]
Gotcha, sorry I was calling _.sortByAll instead of _.sortByOrder.  _.sortByOrder is working fine.

http://codepen.io/ItsLeeOwen/pen/YPjGOv?editors=101

**Comment by octref** [comment]
No problem :-)

**Pull request merged**
