### PR TITLE
rename flattenDepth to flat #3998

### PR DESCRIPTION
**Pull request by Brantron**

### CODE REVIEW

**Comment by jdalton** [comment]
@Brantron Thank you! I believe it's `flat` not `flatt`.
See https://github.com/tc39/proposal-flatMap#arrayprototypeflatflatmap

**Comment by Brantron** [comment]
awesome, should be good now 👍

**Comment by jdalton** [comment]
Thanks! You'll need to rename the module files too.

**Comment by Brantron** [comment]
Hmm, not sure I understand. I renamed `flattenDepth` to `flat`, which other files should be renamed?

**Comment by giulliano-bueno** [comment]
Hey @Brantron, is this PR still valid? Should you consider closing it, please? Thanks.

**Pull request closed without merging**
