### PR TITLE
Add `_.isAll` and `_.isAny`

### PR DESCRIPTION
**Pull request by jlmorgan**
* Added private `createConditional` which creates the `_.isAll` and `_.isAny` functions.
* Added associated tests.

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @jlmorgan! Thanks for this but I'm not wanting to add these at the moment. I wonder if there's a lower level utility underneath these that could be used to compose these.

**Comment by jlmorgan** [comment]
Forgive my ignorance, but I am unable to see which of the existing methods would provide `&&`ing or `||`ing the results of each method call together for a singular value.

**Comment by StreetStrider** [comment]
@jlmorgan, please, tell, which functions you want:
1. functions act like wrappers around `||`, `&&` operators
2. functions act like conjunction and disjunction for predicates
?

**Comment by StreetStrider** [comment]
May be related to #1072.

**Comment by jlmorgan** [comment]
@StreetStrider : actually, either of those would be fine. Just something to take multiple boolean functions to make a new semantic one that represents those things.

**Comment by StreetStrider** [comment]
You should take a look at discussion above. Also, maybe you'll find interesting functions I've implemented:
`negate` (as in LoDash), `conj` and `disj` (as `isAll` & `isAny`): https://github.com/StreetStrider/aux.js/commit/02285f9095f07aaa113e1bd6319c5745b55342c8
This functions implement case (2).

As for case (1), take a look at [Ramda](http://ramdajs.com/docs/)'s logic group of functions. Ramda also implements (2) too. There're cases when you can simply reduce this stuff to Array's `some` & `any` (but in loss of laziness).

**Pull request closed without merging**
