### PR TITLE
Add lazy `uniq`.

### PR DESCRIPTION
**Pull request by qsona**
Hi, this is the implementation of #912 .
One test failed, but it seems to be a bug of slice ( #955 .)

I'll welcome any comments, including some corrections of my poor English (variable name and comment).
Thank you.

### CODE REVIEW

**Comment by qsona** [comment]
I have signed CLA now.

**Comment by jdalton** [comment]
Thank you for the implementation example. We already have optimizations in place for `_.uniq` and the code required to lazyify it is substantial so I think we'll pass on adding it.

**Comment by qsona** [comment]
@jdalton Thanks for checking it. 
My use case is that execute uniq to array which has 100~150 elements and then get first 6 element, so I thought it would be nice to evaluate lazily. But I also worried about the performance problem on this implementation. Anyway, I appreciate you because it was so nice experience to read your codes and implement it. Thank you.

**Comment by jdalton** [comment]
You're feedback on issues found while working on this has been super valuable too. And now that you've signed the CLA you're good for all future contributions.

**Comment by qsona** [comment]
Thanks, I'll try to continue contributing :)

**Pull request closed without merging**
