### PR TITLE
Adding new math method - mode

### PR DESCRIPTION
**Pull request by SHAHRUKH-KHAN**
This pull request is to add a method which would return the mode of the array of numbers.

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks, but you should bring a feature up as an issue first and allow it to be voted on before jumping into a PR. See [our contributing text on feature requests](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by jdalton** [comment]
Signing the CLA is still doable though. It's a one and done thing so you don't have to worry about it next time.

**Comment by SHAHRUKH-KHAN** [comment]
Related to a new issue
[https://github.com/lodash/lodash/issues/2184](url)

**Comment by SHAHRUKH-KHAN** [comment]
@jdalton  
I registered with CLA
still this error persists.

**Comment by dmethvin** [comment]
The [error message](http://contribute.jquery.org/CLA/status/?owner=lodash&repo=lodash&sha=f72a478c32d97f71b5afe4bc75d3cde45bc0d28a) which is [linked from the bot's reply above](https://github.com/lodash/lodash/pull/2182#issuecomment-203804162) says the commit was signed with `users.noreply.github.com`which is not a valid email address.You can fix this by changing your git configuration, updating with `git commit --amend`, and doing a `git push --force` to update this PR.

**Comment by SHAHRUKH-KHAN** [comment]
@dmethvin I am trying to find my commit id.
I have checked out to lodash:master and trying to search commit id for this branch, but no results.
Moreover, when I first opened this PR, I made changes in its github files itself that is why you will see PR name as `SHAHRUKH-KHAN:patch-1`
How to correct al this mess ?

**Comment by jdalton** [comment]
See https://github.com/SHAHRUKH-KHAN/lodash/tree/patch-1 for your branch and its commit hash:
```bash
git clone https://github.com/SHAHRUKH-KHAN/lodash
cd ./lodash
git checkout patch-1
#change your git config settings
git commit --amend
git push origin +patch-1
```

**Comment by SHAHRUKH-KHAN** [comment]
@jdalton I did and was able to checkout. I pushed a code change but it is not getting reflected here.
It is getting reflected in  SHAHRUKH-KHAN/lodash/tree/patch-1 
which is obvious but when i check the commit it ask me to create a PR . Should I ? ;)

**Comment by jdalton** [comment]
@SHAHRUKH-KHAN Don't worry about it this go around.

**Comment by SHAHRUKH-KHAN** [comment]
@jdalton what was the issue, din't get you !

**Pull request closed without merging**
