### PR TITLE
Add removePrefix and removeSuffix methods

### LINKED ISSUE #5038: New methods: removeStart and removeEnd
Inspired by [Python 3.9's `removeprefix` and `removesuffix`](https://dev.to/delta456/python-removeprefix-and-removesuffix-34jp).

These methods are different from `trim{Start|End}` because `remove{Prefix|Suffix}` will only remove if the string starts with the specified substring:

```js
_.trimStart('-_-abc-_-', '_-');
// => 'abc-_-'

_.removePrefix('-_-abc-_-', '_-');
// => '-_-abc-_-'
```

Another difference is that `remove{Prefix|Suffix}` has a second mandatory parameter, where trim's methods default to `whitespace`.

### PR DESCRIPTION
**Pull request by felipecrs**
Closes #5038.

### CODE REVIEW

**Comment by felipecrs** [comment]
I decided to use `prefix` rather than `start`, so I can name the second parameter as `prefix`.

**Comment by felipecrs** [comment]
This is a WIP, not ready to review.

**Comment by felipecrs** [comment]
Thanks @Ramnmo for the [implementation suggestion](https://github.com/lodash/lodash/issues/5038#issuecomment-749799215).

**Comment by felipecrs** [comment]
@jdalton, is there any reason why this was closed?

**Comment by jdalton** [comment]
Hi @felipecrs! It's been a few years. I'm declaring issue bankruptcy to clear the slate a bit.

**Comment by felipecrs** [comment]
Got it. Should I reopen the issue or resend the PR?

**Comment by felipecrs** [comment]
I'm just saying because I believe this PR adds a very useful functionality that many people could benefit of.

**Pull request closed without merging**
