### PR TITLE
Link to the final ES6 spec

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by jdalton** [comment]
Yes! Did you check the hashes to see if they align?

**Comment by jdalton** [comment]
Also, can you rebase. I caused a little clutter.

**Comment by mathiasbynens** [comment]
Yep, they all do! 

Uh, something happened to the diff here

**Comment by mathiasbynens** [comment]
Done.

**Comment by jdalton** [comment]
Thank you!

**Pull request merged**
