### PR TITLE
Created isNullOrUndefined

### PR DESCRIPTION
**Pull request by KhurramJalil**
Created a new file isNullOrUndefined for verifying whether the values passed in the parameter is null or undefined.

### CODE REVIEW

**Comment by KhurramJalil** [comment]
@jdalton, @jashkenas, @falsyvalues, @bnjmnt4n @blikblum Can anyone of you please review/approve this PR.

**Comment by falsyvalues** [comment]
There is [isNil](https://lodash.com/docs/4.17.15#isNil).

**Comment by KhurramJalil** [comment]
@falsyvalues 
I just checked and isNil doesn't check for both null and undefined. It just check for null.
See line #20 in the image below for reference.
image

**Comment by falsyvalues** [comment]
@KhurramJalil https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#comparing_equality_methods

**Comment by KhurramJalil** [comment]
Thanks @falsyvalues for sharing the valuable link for me to revalidate the following.

(null == undefined) returns true but (null === undefined) returns false.

**Pull request closed without merging**
