### PR TITLE
Added missing most commonly used statistical functions

### PR DESCRIPTION
**Pull request by abibell**
Added mode, median, variance and standardDeviation plus the "By" variants - #2284 #2184 

### Tests
Since the master branch tests are in flux as per https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md, I am unable to add tests. You can do it yourself or I can add when test running issue is resolved.

### CODE REVIEW

**Comment by abibell** [comment]
I signed the CLA with my Github account. I can't understand why it still thinks it is not signed. I made sure the email was set too later.

**Comment by jdalton** [comment]
Thanks for this @abibell!

This is great but I want to hold off on adding these methods for now. I think these would probably be better suited/supported in a lib specifically for these types of methods.

As for the CLI see [this](https://cla.js.foundation/lodash/lodash?pullRequest=3906)

**Comment by abibell** [comment]
@jdalton 

- **CLA** Maybe there is a defect in CLA. I don't see any action buttons on here. I already signed it. capture Please advise
- **Library** I am trying to understand your reasoning. lodash currently supports some of the methods - sum, min, max and mean. What is this library you are referring to? By the looks of it, enough people have voted for a median method. Are you suggesting they don't belong in lodash or they don't belong in lodash's Math category? I am sorry I am trying to understand the specific tangible reasoning.

**Comment by jdalton** [comment]
Ah boo. It should have shown what was causing the CLA fail. It usually comes down to your commit email/user not matching with the user of the commit.

**Pull request closed without merging**
