### PR TITLE
Make `isEmpty` method faster on objects

### PR DESCRIPTION
**Pull request by nkt**
Here is the benchmark: http://jsperf.com/fastest-check-if-object-is-empty/2.

### CODE REVIEW

**Comment by jdalton** [comment]
I can see optimizing it a bit, maybe not like this but I'll kick it around a bit.

**Comment by nkt** [comment]
The main idea is that current algorithm has `O(n)` complexity, when it could be `O(1)`.

**Comment by jdalton** [comment]
Have you signed [our cla](http://dojofoundation.org/about/cla)?

**Comment by nkt** [comment]
Yes, as `nkt`, just now.

**Pull request closed without merging**
