### PR TITLE
fix: deleted test/concat.js

### PR DESCRIPTION
**Pull request by Cadienvan**
This test can't pass as the library doesn't provide this function. Suggested in #5573

### CODE REVIEW

**Review by Gauravms2143 — APPROVED** [review]
LGTM👍

**Comment by Cadienvan** [comment]
Guys is the library abandoned?

**Comment by Seven-Y-Q-Guo** [comment]
@Cadienvan _.concat is still available from [here](https://lodash.com/docs/4.17.15#concat), you may need to put concat.js back rather than deleting it.

**Comment by Seven-Y-Q-Guo** [comment]
We can't find it based on master branch, but if you checkout 4.17 branch, concat method will be there.

https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/lodash.js#L6975

You see both lodash official doc and 4.17 branch have `concat.js`.
I think they forgot `concat.js` by mistake, That's why I suggest you can implement `concat.js` on master branch.

**Comment by Seven-Y-Q-Guo** [comment]
If you check the test script in package.json
```
"test": "mocha -r esm test/*.test.js"
```
They just test those files which filename contains the keyword `test`, that means those files(not only concat.js) which not have the keyword `test` are not ready to be tested.

**Comment by Cadienvan** [comment]
Oh got ya, I'd love to go further with it but it's clear this project is totally abandoned, all branches haven't been touched for at least 2 years..

**Comment by Seven-Y-Q-Guo** [comment]
haha, I see

**Pull request closed without merging**
