### PR TITLE
fix(getFuncName): check if value is array instead of truthy

### PR DESCRIPTION
**Pull request by steelsojka**
PR for issue https://github.com/lodash/lodash/issues/1808

(submitted a CLA on 2015-05-28 16:04:11)

### CODE REVIEW

**Comment by jdalton** [comment]
@steelsojka Can you add a unit test and change the `isArray` check to a `hasOwnProperty.call(realNames, result)` kind of check.

**Comment by jdalton** [comment]
It would help me out a lot.

**Comment by steelsojka** [comment]
@jdalton Sure can.

**Comment by steelsojka** [comment]
I wrote the test as part of the curry suite, since this is how it was detected. Not sure how else to test it. If you remove the fix the test fails.

**Comment by jdalton** [comment]
Perfect, thanks!

**Pull request merged**
