### PR TITLE
Make _.isEmpty work as expected on buffers

### PR DESCRIPTION
**Pull request by fdegiuli**

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @fdegiuli!

Thanks for this PR! I can dig it.
You're the first dev to hit the jQuery bot. It's checking if you've signed [our CLA](http://contribute.jquery.org/CLA/)

**Comment by jdalton** [comment]
On review a buffer will be detected as array-like by `isArrayLike` so should hit the code path anyways (tested in Node 0.10 and Node 5.0).

**Comment by fdegiuli** [comment]
The problem is that the checks after `isArrayLike` only allow for arrays, strings, functions, and arguments (because of the `&&`) So even though a buffer `isArrayLike`, it never reaches the return statement.

Here's what it looks like in the cli:

```
nesh> var u = require('lodash');
undefined
nesh> buf = new Buffer('');
<Buffer >
nesh> buf.length
0
nesh> u.isArrayLike(buf);
true
nesh> u.isEmpty(buf)
false
```

I have a new commit that clarifies this and adds a test case, I can open a new PR, if you want. (I guess github doesn't update closed PRs)

**Comment by jdalton** [comment]
Ah, thanks for clarifying.
We don't currently support iterating buffers so returning `false` for `_.isEmpty` would be misleading:

> Checks if `value` is an empty object or collection. A value is considered
empty if it's an `arguments` object, array, string, or jQuery-like collection
with a length of `0` or has no own enumerable string keyed properties.

**Comment by fdegiuli** [comment]
I don't quite follow. Right now calling `isEmpty` with a buffer _always_ returns `false`.  Are you saying that we should change it, or that `isEmpty` shouldn't work on buffers at all?  In that case, maybe `false` is the wrong thing to return anyway?

**Comment by jdalton** [comment]
Wow hmm I'm messing this up pretty well :)
I forget that buffers in Node land are just typed arrays and we support typed arrays. You shouldn't need to remove the `isArrayLike` check just add an `isBuffer` check to the mix.

**Comment by jdalton** [comment]
@fdegiuli Rock now it's just the CLA bit.

**Comment by fdegiuli** [comment]
Ah, of course. Buffers only exist in node. Let me fix that.

**Comment by jdalton** [comment]
:tada: Thanks for your patience!

**Comment by fdegiuli** [comment]
My pleasure. Thanks for the quick replies.

**Comment by fdegiuli** [comment]
Looks like the build is failing because I used `assert(true)` instead of `skipAssert` I've fixed it if you want to reopen this a second time... Sorry about that.

**Comment by fdegiuli** [comment]
Wait, it's been merged. Should I open a new PR?

**Comment by jridgewell** [comment]
@fdegiuli: He's [already fixed it](https://github.com/lodash/lodash/commit/43942356e85385d1a4570e3728025632ea8af122). :wink:

**Comment by fdegiuli** [comment]
Sweet.

**Comment by jdalton** [comment]
No worries. I've got your back.

**Pull request merged**
