### PR TITLE
adding math subtract

### PR DESCRIPTION
**Pull request by J3remyD**

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @J3remyD! Have you signed [our CLA](http://dojofoundation.org/about/claForm)?

**Comment by J3remyD** [comment]
Hi @jdalton ,
yes indeed I have

**Comment by jdalton** [comment]
Opinions on the name? Would `minus` do?

**Comment by StreetStrider** [comment]
@jdalton, maybe `_.sub`?
add ↔ sub. `subtract` is also ok, `sub` just shorter. Have looked in Ramda, they called it [subtract](http://ramdajs.com/docs/#subtract) as in PR.

**Comment by jdalton** [comment]
I want to avoid `sub` as that can be seen as a shorthand for [substitute](http://api.prototypejs.org/language/String/prototype/sub/).

**Comment by jdalton** [comment]
@J3remyD Do you have a use case for `_.subtract`?

**Comment by J3remyD** [comment]
@jdalton I agree with you that sub could sometimes be misleading even though it's shorter and sounds great ; that's why I named it thinking with the same pattern like add is for addition I figured subtract would be for subtraction.

**Pull request merged**
