### PR TITLE
fix findKey returning the value instead of the key

### PR DESCRIPTION
**Pull request by dan-dr**

### CODE REVIEW

**Comment by dan-dr** [comment]
well that license bot doesn't seem to like me very much no point in forcing it ¯\_(ツ)_/¯

**Comment by dan-dr** [comment]
ah you already committed it. byebye PR

**Comment by jdalton** [comment]
Dup of #3301.

@dan-dr No worries. We'll tackle it again next time 😃

**Comment by dan-dr** [comment]
future possible employers I found this bug!! they've blatantly stolen my PR!! hire me plz :full_moon_with_face:

**Comment by falsyvalues** [comment]
:smiley:

**Pull request closed without merging**
