### PR TITLE
Little doc correction for _.endsWith().

### PR DESCRIPTION
**Pull request by arendjr**

### CODE REVIEW

**Comment by arendjr** [comment]
CLA should be signed now.

**Comment by jdalton** [comment]
@arendjr See http://contribute.jquery.org/CLA/status/?owner=lodash&repo=lodash&sha=91811ffd45d680cade4d026249f8915f9aa924ab (make sure your name matches that on your commit)

**Comment by jdalton** [comment]
More info on how to resolve the issue is in the linked page.

**Comment by arendjr** [comment]
Thanks!

**Comment by jdalton** [comment]
Thank you!

**Pull request merged**
