### PR TITLE
WIP: StringWrapper implementation for #1016

### PR DESCRIPTION
**Pull request by octref**
#1016 

Just an attempt. Still **WIP**.
I'd like to get some feedback before going too deep, in case I did something wrong.
No `split` and `replace` yet.

### What you can do now?
```
_("hiya")
// -> StringWrapper {__wrapped__: "hiya", __actions__: Array[0], __chain__: true, constructor: function, after: function…}
_("hiya").capitalize().value()
// -> "Hiya"
_("hiya").capitalize().pad(6, '_').repeat(5).value()
// -> "_Hiya__Hiya__Hiya__Hiya__Hiya_"
_("hiya").capitalize().pad(6, '_').repeat(5).words().value()
// -> ["Hiya", "Hiya", "Hiya", "Hiya", "Hiya"]
```

One question I have:
#### Any better idea to detect if an `action` is a String method?
  - In `baseStringWrapperValue`, I listed all string methods to check if the actions are string methods.
This is definitely not a good solution as we'd have to change this when we add new string methods.
  - In `baseStringWrapperValue`, I'm using `action.func.name` to check the function name, however, for methods like `camelCase` which uses `createCompounder` to return a anonymous func, it's empty.
I'm allowing anonymous functions to be performed now.

Those kind of tests don't pass for now, as expected:
```
    test('should return an unwrapped value when implicitly chaining', 1, function() {
      if (!isNpm) {
        strictEqual(_('fred').capitalize(), 'Fred');
      }
      else {
        skipTest();
      }
    });
```

I'll fix tests later.  (submitted a CLA on 2015-02-21 03:34:30)

### CODE REVIEW

**Comment by jdalton** [comment]
Eeeek totally wrong direction here. We don't want to change the chaining behavior. Devs can use `.chain()` to force chaining of strings.

**Comment by jdalton** [comment]
See [here](https://github.com/lodash/lodash/blob/3c01ecccc4a85fdef406da1f6aa45d72041cec03/lodash.src.js#L11710). The idea would be to just add `'split', 'replace'` to values and a regexp to detect them, `/^(?:replace|split)$/` to determine which built-in prototype to use `arrayProto` or `stringProto`.

**Comment by octref** [comment]
What if the `LodashWrapper` is not a string? I thought we should only allow functions in String section to be chained when the wrapped value is a string.

**Comment by jdalton** [comment]
You can currently pass junk to all our methods, we throw in only a select few cases.

**Comment by octref** [comment]
OK. I was overthinking it. Thanks for your pointer! I'll try to do it again tmr as you suggested.

**Comment by jdalton** [comment]
You don't have to close this, you can rebase it.

**Comment by octref** [comment]
Sure. 
BTW I was thinking maybe `replace` would be a good addition #1022 .

**Comment by octref** [comment]
Just wondering. Do you have a reason to keep these non-capturing groups `?:` ?
```
isStringFunc = /^(?:split|replace)$/.test(methodName),
chainName = /^(?:push|sort|unshift)$/.test(methodName) ? 'tap' : 'thru',
fixObjects = !support.spliceObjects && /^(?:pop|shift|splice)$/.test(methodName),
retUnwrapped = /^(?:join|pop|shift)$/.test(methodName);
```

**Comment by jdalton** [comment]
> Do you have a reason to keep these non-capturing groups ?:

Makes it clear my intent, not concerned over the few characters it costs.

**Pull request merged**
