### PR TITLE
run tests concurrently

### PR DESCRIPTION
**Pull request by craigmichaelmartin**

### CODE REVIEW

**Comment by Xotic750** [comment]
You may want to look at parallelshell https://www.npmjs.com/package/parallelshell

**Comment by craigmichaelmartin** [comment]
Yeah, if there is openness for it. This seems pretty straightforward, though.

**Comment by jdalton** [comment]
This would jumble the results as they report as they're executing. I dig the pretest addition though. If you limit it to just the pretest change I'll merge.

**Comment by craigmichaelmartin** [comment]
Sure thing! However, I thought the output for this looked looked fine (sorry for the large pictures)

In parallel:
screen shot 2016-01-28 at 3 14 31 pm

In series:
screen shot 2016-01-28 at 3 13 26 pm

**Comment by jdalton** [comment]
> However, I thought the output for this looked looked fine

That's because there are no failures.

**Comment by craigmichaelmartin** [comment]
Haha, good point!! :smile:

**Comment by jdalton** [comment]
Signing [our cla](http://dojofoundation.org/about/cla) isn't required for this but would be good for future contributions.

**Pull request merged**
