### PR TITLE
Fixing other vulnerabilities 

### PR DESCRIPTION
**Pull request by Alec321**
Also I'm not sure why the project is dependent on itself. Can't we remove it and have the user that needs it to bring it in elsewhere?

### CODE REVIEW

**Comment by jdalton** [comment]
Hey @Alec321!

I'm not interested in anymore of these style of PRs. Thanks.

**Comment by Alec321** [comment]
Hey @jdalton,
I apologize I didn't see a pull_request_template and wasn't sure how you wanted a PR styled.
Best,
Alec

**Comment by Alec321** [comment]
@jdalton My bad I'll follow the contribution guidelines. I didn't see that before that's my bad.

**Comment by jdalton** [comment]
No worries. I was writing more to the fact that Lodash is a zero dependency package. Our dev dependencies do not impact consumers as a whole. I'm OK with having potential vulnerabilities in dev deps as they won't likely affect us and our use case for them.

**Pull request closed without merging**
