### PR TITLE
 Re-add keysIn module fixing baseClone and baseMerge (#4099) 

### LINKED ISSUE #4099: baseMerge and baseClone does not works because of missing keysIn
baseMerge and baseClone imports keysIn which does not exists anymore

For the record baseKeysIn was removed [here](https://github.com/lodash/lodash/commit/58e484f389762750a13b0d8f952eb80235a31649)

should baseKeysIn be restored or do the same as [here](https://github.com/lodash/lodash/commit/58e484f389762750a13b0d8f952eb80235a31649#diff-5c9720962ba84f94900532fc93850ba5L12)?

### PR DESCRIPTION
**Pull request by blikblum**
Fixes #4099 

Since keysIn is passed along as a variable, i needed to create a local function instead of using key-in in place

### CODE REVIEW

**Comment by jdalton** [comment]
Welp, you might as well make it its own module.

**Comment by blikblum** [comment]
A public or an internal one?

**Comment by jdalton** [comment]
Let's go external.

**Comment by blikblum** [comment]
Done

**Comment by jdalton** [comment]
Thank you!

**Pull request merged**
