### PR TITLE
Add reverce function calls order for debounce method

### PR DESCRIPTION
**Pull request by alexsanya**

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @alexsanya!

Can you describe the feature a bit?

**Comment by alexsanya** [comment]
Hi, @jdalton In current implementation of `debounce` method only last arguments list remembers

**Comment by alexsanya** [comment]
Hi @jdalton

**Comment by alexsanya** [comment]
Hi, @jdalton! 
In current implementation `debounce` remembers only arguments list from the most recent call. But in some situation arguments list from the earliest call have to be applied instead. For example:
Standard behavior:
```
500 Put to stack callback(1)
1002 Put to stack callback(2)
1502 Put to stack callback(3)
2005 Put to stack callback(4)
2501 Run callback(4)
2506 Put to stack callback(5)
3012 Put to stack callback(6)
3513 Put to stack callback(7)
4014 Put to stack callback(8)
4509 Run callback(8)
4515 Put to stack callback(9)
5016 Put to stack callback(10)
5517 Put to stack callback(11)
6519 Run callback(11)
```
Option `{lazy: true}` effects behavior this way:
```
500 Put to stack callback(1)
1002 Put to stack callback(2)
1502 Put to stack callback(3)
2005 Put to stack callback(4)
2501 Run callback(1)
2506 Put to stack callback(5)
3012 Put to stack callback(6)
3513 Put to stack callback(7)
4014 Put to stack callback(8)
4509 Run callback(5)
4515 Put to stack callback(9)
5016 Put to stack callback(10)
5517 Put to stack callback(11)
6519 Run callback(9)
```

**Pull request closed without merging**
