### PR TITLE
Fixed broken link in README.md

### PR DESCRIPTION
**Pull request by realdubb**
Fixed broken link for lodash/fp in README

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks, but I'm just waiting to tag the release is all.

**Comment by realdubb** [comment]
Thanks for the reply! I'll get my cla in order for future contributions

**Comment by jdalton** [comment]
I'll keep it open while you do that :)

**Comment by realdubb** [comment]
All done, I appreciate it!

**Comment by jdalton** [comment]
Moved to #2474.

**Comment by jdalton** [comment]
Closed via https://github.com/lodash/lodash/commit/2a49d4a9e9773142a23fb9a59dae87ea958eb617.

**Pull request closed without merging**
