### PR TITLE
Add `_.isJSON` function

### PR DESCRIPTION
**Pull request by hairyhenderson**
Here's an `_.isJSON` function to help clean up code that would otherwise be littered with `try { JSON.parse(...); } catch (e) { }`.

I'm pretty sure that the performance of this function could be improved, but this is a simple first cut.

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @hairyhenderson!

You can use

```js
if (!_.isError(_.attemp(JSON.parse, value))) {
```

I'll keep an eye on this request to see if it gets traction.

**Comment by hairyhenderson** [comment]
Thanks @jdalton - I wasn't aware of `_.attempt`. I still think something like

```js
if (_.isJSON(value)) {
```

is a lot cleaner.

Also, `JSON.parse` actually won't throw on certain non-JSON inputs (by which I mean inputs which aren't strictly valid JSON strings - I'm thinking of `JSON.parse(null)` or `JSON.parse(42)`, which return `null` and `42` even though they _aren't JSON strings_.

**Comment by jdalton** [comment]
In the meantime you can create a `mixin`.

**Comment by hairyhenderson** [comment]
@jdalton - good point, thank you!

**Pull request closed without merging**
