### PR TITLE
Add `findIndexFrom` and `findLastIndexFrom` in FP.

### LINKED ISSUE #2329: Add `_.findIndexFrom` and `_.findLastIndexFrom` in Lodash/fp
The `fromIndex` param has been (re-)added to `_.findIndex` and `_.findLastIndex` in master, but the functionality is not available in `lodash/fp`.

I'm proposing `_.findIndexFrom(predicate, fromIndex, array)` for the param order.

Willing to try my hand at adding it :)

### PR DESCRIPTION
**Pull request by jfmengels**
Add `findIndexFrom` and `findLastIndexFrom` in FP. Closes #2329

I've added tests to make sure the iteratee was capped, wasn't sure that it would take the capping of its alias method, so better safe than sorry. And I've tried to make the tests look like the rest (`_.each`-y), I hope it doesn't make them too hard to understand.

### CODE REVIEW

**Comment by jdalton** [comment]
Up for adding `indexOf` and `lastIndexOf` forms too?

**Comment by jfmengels** [comment]
Sure, `indexOfFrom` and `lastIndexOfFrom`? (Man that's a mouthful)

**Comment by jdalton** [comment]
Yep!

**Comment by jfmengels** [comment]
Tada!

**Comment by jdalton** [comment]
Thanks!

**Comment by jfmengels** [comment]
My pleasure :)

I see that `_.includes` also has a `fromIndex` method, might as well add it now too right?

By the way, I noticed that `_.find` doesn't have a `fromIndex` param that could be useful. Is that not available because it should also work on object?

**Comment by jdalton** [comment]
> Is that not available because it should also work on object?

Right, which is why `includes` doesn't have it either. Collections methods. It's why in v5 we're splitting them all up.

**Comment by jdalton** [comment]
Oh wait. We have it for `includes` and just shrug for objects. I guess we can do the same for `find` too.

**Comment by jfmengels** [comment]
Yeah it has it. I'd be :+1: for that, sounds pretty useful to me

**Comment by jfmengels** [comment]
Btw, are we :+1: with adding aliases to all methods with optional params? I see `result` that could have a `resultOr` friend, and I'm sure there are others. If we do want that, then I could make PRs as I find them.

**Comment by jdalton** [comment]
> Btw, are we :+1: with adding aliases to all methods with optional params?

There are lots of variadic methods which could use alternatives. For now I'm going with the approach of waiting until the request comes in.

**Comment by jfmengels** [comment]
Sure. Let me know if you want me to add others

**Pull request merged**
