### PR TITLE
Escape the backtick in escape description

### PR DESCRIPTION
**Pull request by mohsen1**
Noticed this little odd rendering in API docs
screen shot 2015-02-27 at 10 06 30 am

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks, all you have to do is escape the `\`` in '\`'

**Comment by mohsen1** [comment]
I noticed other methods don't wrap characters between backticks, but I'm not sure how it's possible to escape a backtick when it's not a inline code block.

**Comment by mohsen1** [comment]
This is another way of doing it:

Converts the characters "&", "<", ">", '"', "'", and "`` ` ``", in `string` to

**Comment by jdalton** [comment]
> Converts the characters "&", "<", ">", '"', "'", and "`", in string to

Let's go that route. I've fixed this on site.

**Comment by mohsen1** [comment]
Updated the commit with that

**Comment by jdalton** [comment]
Have you signed our [CLA](http://dojofoundation.org/about/claForm)?

**Comment by jdalton** [comment]
Actually on second look simply escaping with \` works. Maybe not in github comments but in markdown in genera). See https://gist.github.com/jdalton/985387ddf9fd4e67cd21

**Comment by mohsen1** [comment]
signed the CLA and updated the commit. I didn't know backslash escaping works in Markdown. Good to know!

**Pull request merged**
