### PR TITLE
add git hook instructions to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kentcdodds**
Happy to change any wording and stuff :-)

### CODE REVIEW

**Comment by kentcdodds** [comment]
@jquerybot `¯\_(ツ)_/¯` do I need to sign the CLA for every PR? #2146

**Comment by dmethvin** [comment]
Yes, if you change email addresses. `kent+github` is not the same as `kent`.

**Comment by kentcdodds** [comment]
Ah, whoops... Was messing around with my `git` config yesterday. :+1:

**Comment by kentcdodds** [comment]
Fixed. Thanks @dmethvin :-)

**Comment by jdalton** [comment]
This is great. Thank you!

**Pull request merged**
