### PR TITLE
improvisation - Added filler option for chunk method

### PR DESCRIPTION
**Pull request by ashwinspg**

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @ashwinspg!

The CLA bot is not detecting a proper sign.

**Comment by ashwinspg** [comment]
Hi @jdalton 

what to do for the proper sign?

**Comment by jdalton** [comment]
Make sure that your commit has your username and email associated with it that you use for github. You can see that the commit avatar and your user avatar are different so GitHub sees that has being 2 different users. You can just rebase the commit with the amended author info and then force push.

**Comment by ashwinspg** [comment]
sure will do that :)

**Comment by jdalton** [comment]
Checking in

**Comment by ashwinspg** [comment]
I will make the pull request again

**Comment by ashwinspg** [comment]
check out the merge request: https://github.com/lodash/lodash/pull/4547

**Pull request closed without merging**
