### PR TITLE
Remove length variable and additional if-else statement in `_.last`

### PR DESCRIPTION
**Pull request by arthurkhu**
We don't need additional if-else statement and variable.
Here is a benchmark, this way is good too: http://jsperf.com/lodash-f-last

### CODE REVIEW

**Comment by d10** [comment]
The current behaviour is intentional because lodash tries to avoid throwing errors. By using the current behaviour, errors will not be thrown if say `array` is `undefined`.

**Comment by arthurkhu** [comment]
@d10 current version and my version return the same result if array is undefined. 
In current version `var length = array ? array.length : 0;` — If array is false length is `0`. 
Next line: `length ? array[length - 1] : undefined;` If length is false (0 is false) then return `undefined`. 
My version: `return array ? array[array.length - 1] : undefined;`. If array is false then return `undefined`. Can I have an example, what you mean?

**Comment by d10** [comment]
Try running `_.last(undefined)`.

**Comment by jridgewell** [comment]
See http://jsperf.com/lodash-f-last/2

There's a deopt when grabbing the last item in an empty array with your implementation.

**Comment by arthurkhu** [comment]
@d10 result is `undefined` in current version and my version. https://jsfiddle.net/z4vuj2a9/

**Comment by d10** [comment]
Facepalm! @arthurkhu you're right, my brain is dead already.

**Comment by arthurkhu** [comment]
@d10 Don't worry about it. If it's possible, please, reopen pull request, we can see, what other contributors think

**Comment by jridgewell** [comment]
> If it's possible, please, reopen pull request

[See above](https://github.com/lodash/lodash/pull/1130#issuecomment-92879221). You're prioritizing performance over correctness, and it kills a common case.

**Comment by jdalton** [comment]
Hi @arthurkhu! The others have expressed the gist of why I wouldn't do this. The method should accept falsey values and we want to ensure if an array is passed and is empty that it doesn't access the `-1` property. The performance gain is insignificant (millions compared to more millions of operations a second) so there's no clear win to changing the behavior.

**Comment by arthurkhu** [comment]
Hi @jridgewell @jdalton. My bad with read out of bounds. I can fix it with `return (array && array.length > 0) ? array[array.length - 1] : undefined;` and it's also faster, but of course, it's microoptimization.

**Comment by jdalton** [comment]
Naw, it's ok the way it is.

**Pull request closed without merging**
