### PR TITLE
added check for NaN

### PR DESCRIPTION
**Pull request by saurabhg22**

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @saurabhg22!

The current behavior is by design.

**Comment by StreetStrider** [comment]
@saurabhg22 `NaN` is a number. You probably look for `isFinite`.

**Comment by saurabhg22** [comment]
Thanks, but still don't understand how "Not A Number" is actually a number.

**Comment by StreetStrider** [comment]
@saurabhg22 it's a special value, however it belongs to number domain. Just like `Infinity` and `-Infinity`. This is related to a standart on top of which JS' number is founded (look for IEEE 754).

**Pull request closed without merging**
