### PR TITLE
_.every and _.some short-circuit evaluation

### PR DESCRIPTION
**Pull request by miromannino**
It is not clear if the `_.every` function always iterates all the
collection or if it stops at the first falsy value; the `_.some` function
documents this feature, and that creates even more confusion. 

I documented the `_.every` function in this sense. I also have updated 
the tests for `_.some` and `_.every` to evidence this feature.

### CODE REVIEW

**Comment by d10** [comment]
LGTM, although the tests could probably be simplified to avoid multiple runs of `_.every` and `_.some`.

**Comment by jdalton** [comment]
Thanks @miromannino! Have you [signed our CLA](http://dojofoundation.org/about/claForm)?

**Comment by miromannino** [comment]
Hi @jdalton, now I have signed it.

**Comment by jdalton** [comment]
Closed via https://github.com/lodash/lodash/commit/82ccc5c6a980746f960a0288955cb68a4fee66f6.

**Pull request closed without merging**
