### PR TITLE
Add `_.isNil`  function

### PR DESCRIPTION
**Pull request by xixilive**

### CODE REVIEW

**Comment by jdalton** [comment]
@xixilive Have you signed our [CLA](http://dojofoundation.org/about/claForm)?

**Comment by xixilive** [comment]
Signed! @jdalton 
> Your Contributor License Agreement has been received and you are now eligible to contribute to all Dojo Foundation projects. Thank you for your contribution!

**Comment by jdalton** [comment]
Thanks!

**Comment by StreetStrider** [comment]
> _.isNil(void 0);
> // => false

Why is that?

```js
js > (void 0) == null
true
```

**Comment by xixilive** [comment]
Why not is that? :smile: 
```
(void 0) === undefined; // true
undefined == true; // true
```

**Comment by StreetStrider** [comment]
@xixilive, the line I was commenting was from your PR, the documentation part of it.

**Comment by xixilive** [comment]
ok, that's a copy & paste bug! thank you @StreetStrider

**Comment by xixilive** [comment]
@jdalton Could you give me a hand for this, please
```
_.isNil(void 0);
// => true
```

**Pull request merged**
