### PR TITLE
More subtle punctuation in documentation menu

### PR DESCRIPTION
**Pull request by Loilo**
Fixes lodash/lodash.com#133, accompanies lodash/lodash.com#134.

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @Loilo! I will probably remove the `_.` bit entirely in future versions.

**Comment by jdalton** [comment]
While I can't merge this into our current master (in it's current state). I will come back to this once we re-wire stuff and cherry-pick it in.

**Comment by Loilo** [comment]
That was the first thing I thought of but didn't want to suggest it. I assumed there'd be some kind of good reasoning behind that. :)

**Comment by Loilo** [comment]
And I can't sign the other pull request (lodash/lodash.com#134) because I've committed with the wrong git credentials. Sigh.

**Comment by jdalton** [comment]
No worries. You can simply rebase your commit with `git commit --amend --reset-author` if you're setup the property `git config user.name` and git config user.email` and then `git push origin +subtle-punctuation`. That should make the robot happy.

**Comment by Loilo** [comment]
Thanks. I assumed that was possible but didn't know howö I've always snuck around the rebase topic. Should probably learn some more advanced git techniques. 👍

**Comment by StreetStrider** [comment]
@jdalton I'm using `_.` for precise and simple text search over documentation.

**Pull request closed without merging**
