### PR TITLE
Document that _.any is an alias of _.some

### PR DESCRIPTION
**Pull request by staticshock**

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @staticshock!

Thanks but we don't have `any` as an alias of `some` in the default module.

**Comment by staticshock** [comment]
Thanks! My mistake.

**Comment by jdalton** [comment]
No problem 😄

**Comment by akshaysmurthy** [comment]
@jdalton I wonder what this test is talking about - https://github.com/lodash/lodash/blob/83ff7d9868649bef9e0c010c2f3dd0bc5276b31b/vendor/underscore/test/collections.js#L402

**Comment by craigmichaelmartin** [comment]
@akshaysmurthy You are looking at underscore's tests.

**Comment by akshaysmurthy** [comment]
@craigmichaelmartin That was so stupid of me 😄

**Pull request closed without merging**
