### PR TITLE
Fixin `value` typo.

### PR DESCRIPTION
**Pull request by falsyvalues**

### CODE REVIEW

**Comment by dejwid** [comment]
👍

**Comment by jdalton** [comment]
@falsyvalues  Thanks for the review!

**Comment by falsyvalues** [comment]
@jdalton :+1:

**Comment by jdalton** [comment]
@falsyvalues I've given you commit rights to `lodash/lodash` feel free to make changes at will unless you have a question on something. It's pre-v5 so there's a lot of freedom at the moment.

**Comment by jdalton** [comment]
The broad goal is to simplify overall and simply through ES6+ syntax where possible.

**Comment by falsyvalues** [comment]
@jdalton Thanks, I appreciate that.

**Pull request merged**
