### PR TITLE
fix doc: "return" to "returns"

### PR DESCRIPTION
**Pull request by think2011**

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks!

**Comment by think2011** [comment]
@jdalton  Could you tell me  how to convert lodash.js to doc HTML? 

I'm using this https://github.com/jldec/lodash-doc-src

**Comment by jdalton** [comment]
We use [php-markdown](https://michelf.ca/projects/php-markdown/) and [docdown](https://github.com/jdalton/docdown). Neither are super great.

**Comment by think2011** [comment]
@jdalton Thank you very much！

**Pull request merged**
