### PR TITLE
The underscore(1.8.3) has method _.all which is  _.every 's alias,but not in lodash

### PR DESCRIPTION
**Pull request by 178220709**
i try to use lodash.js to replace underscore.js
but throw a error , _.all is undefined
http://devdocs.io/lodash/index#every
The doc of lodash said lodash has all too ,but i cant find in code
so i add the _.all method  .
just direct to every

### CODE REVIEW

**Comment by StreetStrider** [comment]
@178220709, which version?
```js
js > lodash.VERSION
'3.10.1'
js > [ lodash.all, lodash.any ]
[ [Function: every], [Function: some] ]
```

**Comment by jdalton** [comment]
As part of our 4.0 work lodash is dropping most of its aliases.

**Comment by StreetStrider** [comment]
@jdalton, that was one of my favorites :C

**Comment by jdalton** [comment]
Aliases are trivial to add, a cleaner, clearer API is a bigger win.

**Comment by StreetStrider** [comment]
@jdalton, ye, agreed, I'm not complaining. It would always be possible to alias it by wish:
```js
var all = require('lodash').every
```

**Comment by 178220709** [comment]
ok , it is not a serious problem.
i will  add a mask to the _ to adapter my old code .

**Pull request closed without merging**
