### PR TITLE
feat(sideEffects): Set sideEffects false for opt.

### PR DESCRIPTION
**Pull request by TheLarkInn**
This adds the webpack v4 sideEffects optimization. Since we are now in alpha I wanted to help ensure this gets out there so people testing webpack v4 can see the instant wins. <3

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks! We'll be sure to backport this too! *(folks hold my feet to the :fire: if I forget)*

**Comment by TheLarkInn** [comment]
👍  Thanks!

**Comment by TheLarkInn** [comment]
Hey @jdalton did you want me to backport this? I'd love to grab this version right now ASAP! lol

**Comment by jdalton** [comment]
I planned on doing backports around the time of Lodash v5 or before webpack v4 goes stable *(whichever comes first)*. Do you have a rough estimate on when webpack v4 will be released?

**Pull request merged**
