### PR TITLE
Implement `same` method

### PR DESCRIPTION
**Pull request by cope**
Implement `same` method

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @cope!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by zaclummys** [comment]
@cope why not using `Array#includes` rather than `difference`?

**Comment by cope** [comment]
@zaclummys I don't have a preference, TBH. I just used the first thing that worked for me.

Do you mean something like `return _.includes(array, values) && _.includes(values, array);`?

If that works, I would agree it's better.

**Comment by zaclummys** [comment]
@cope,

I think `includes` is faster and more effective than `difference`, because the first only checks for the existence of a value rather than creating a new array with new values.

Your snippet looks good! How about adding also `values === array` to check whether both arguments point to the same object?

**Comment by cope** [comment]
I agree.

Would this be acceptable?
```
import includes from './.includes.js'
import forEach from './forEach.js'

function containsAll (a1, a2) {
    let all = true;
    forEach(a2, x => all = includes(a1, x));
    return all;
}

function same (a1, a2) {
    return a1 === a2 ? true : containsAll(a1, a2) && containsAll(a2, a1);
}
```

**Comment by zaclummys** [comment]
@cope,

You don't need to iterate over all values, you can stop the iteration (`break`/`return`)  when a value isn't included. In my snippet, `baseSame` do this trick.

**Comment by zaclummys** [comment]
@cope, looks good!

It just add to my snippet a pre-test `array1.length === array2.length` to help to avoid unnecessary effort.

**Comment by cope** [comment]
Copied the length check from you, that very much makes sense!

**Comment by cope** [comment]
@jdalton Should I somehow update the PR, or should we first wait to see if the popularity of the request is going?

**Comment by StreetStrider** [comment]
I would like to see this method merged. It is obvious that we use arrays here as sets, but builtin array type is still much more convenient and appropriate than `Set` in most of conditions. Besides, `Set` lacks such method either (that's nonsence for such type!). So, basically I still support any methods which allow to work with arrays as sets.

**Comment by simonmilz** [comment]
+1

**Pull request closed without merging**
