### PR TITLE
add enrich array function

### PR DESCRIPTION
**Pull request by J3remyD**
This function enrich every element of a provided array by concatenating
an input parameter value

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @J3remyD. In v4 you'll be able to do `_.map(arr, _.partial(_.add, prefix))`.

**Comment by J3remyD** [comment]
Oh I didn't see that coming :) ! Cool !

**Comment by J3remyD** [comment]
@jdalton would it be possible to combine the same with _.map(arr, _.partial( _.remove,prefix)) and does it handle suffixes to ??

**Comment by jdalton** [comment]
You could could partial a combo of `_.bind` plus a `String#replace` method but it would end up looking pretty gross compared to just writing out a traditional `iteratee`.

**Comment by J3remyD** [comment]
Indeed, thanks.

**Pull request closed without merging**
