### PR TITLE
Explain in CONTRIBUTING that +1 is encouraged for feature requests.

### PR DESCRIPTION
**Pull request by jmm**
Hmm, now I'm confused. I came here to ask you to include this because this is my understanding of your policy from [conversation on Twitter yesterday](https://twitter.com/mccjm/status/700386076880461825). Many projects yell at people for +1'ing issues, so if you don't tell people it's ok a lot of them probably won't do it and the gauge of community interest will be skewed.

But before I submitted I noticed that the whole paragraph on feature requests was just added. I didn't know that before, the timing is a total coincidence. But I noticed that the commit that was merged from the PR adding that paragraph [had this at the end](https://github.com/lodash/lodash/commit/c7727f51e703dd42f933c0f4ce54a2fe5eaea7d3):

>  and leave a comment there if you could find one.

But it's gone from the commit that's in `master` https://github.com/lodash/lodash/commit/b7ae5f088573da15354ead52dddd4383f96daaaa.

Is there a reason that part was removed?

### CODE REVIEW

**Comment by jdalton** [comment]
I didn't like the wording. Your suggested wording is fine. Have you signed [our cla](http://dojofoundation.org/about/cla)?

**Comment by jdalton** [comment]
If you're still interested and have signed the CLA just let me know and I'll merge.

**Comment by captbaritone** [comment]
:+1:

**Comment by jdalton** [comment]
Free free to ping back.

**Comment by jdalton** [comment]
Done via https://github.com/lodash/lodash/commit/a326a6badf9f24691e9d86c50b19994102e7878e.

**Comment by jmm** [comment]
Thanks @jdalton! Wow, you move faster here than I'm used to with other projects. I guess I should've been tipped off by your low open issue / PR counts.

**Pull request closed without merging**
