### PR TITLE
Remove meaningless allocation

### PR DESCRIPTION
**Pull request by KyoungWan**
Remove meaningless allocation

### CODE REVIEW

**Review by bhaveshshah — APPROVED** [review]
LGTM!

**Review by HyunSangHan — APPROVED** [review]
LGTM!

**Comment by rkuykendall** [comment]
This makes a lot of sense. This has two approvals and is very straightforward. @bnjmnt4n @jdalton what is keeping this from being merged?

**Comment by ITSWYoo** [comment]
LGTM 👍

**Review by rkuykendall — APPROVED** [review]

**Review by luoxiu — APPROVED** [review]

**Review by an040702 — APPROVED** [review]

**Pull request closed without merging**
