### PR TITLE
_.every docs: correct ";" to ":"

### PR DESCRIPTION
**Pull request by parkr**
https://lodash.com/docs#every

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks but we've settled on using the `;` for it and other like  lines in the documentation.

**Comment by parkr** [comment]
Ok...? Per my education it's not correct (when you list something, you use a colon to start the list) but maybe you interpret the sentence differently than I do.

**Comment by jdalton** [comment]
stahp

**Comment by d10** [comment]
Thie docs have been updated to use colons instead. See 6c1bc1d7bb814ee9c1fa7bacdcdac3c7ae14e3b0.

**Pull request closed without merging**
