### PR TITLE
Add nonempty

### PR DESCRIPTION
**Pull request by aguspina**

### CODE REVIEW

**Comment by aguspina** [comment]
This function is similar to `nonEmpty` in `scala.collection.immutable.List` from Scala

**Comment by jdalton** [comment]
Thanks for the PR, @aguspina!

This can be tackled with `_.negate(_.isEmpty)`

**Comment by aguspina** [comment]
@jdalton Yeah! I'm actually using this in my projects, but it's quite annoying, don't you think?

**Comment by jdalton** [comment]
I haven't had a problem with doing `if (!_.isEmpty(...)) {`.

**Comment by aguspina** [comment]
Ok, thanks for your answer! Regards!

**Pull request closed without merging**
