### PR TITLE
Added new functionality: filterWhile

### PR DESCRIPTION
**Pull request by 7coder7**
A generalized version of takeWhile and dropWhile

### CODE REVIEW

**Comment by megawac** [comment]
I think this is better handled by composing the two methods, either through a `chain`, where shortcut fusion will apply or through the standard interface `_.filter(_.takeWhile(...), ...)`. Implementing methods like this increase the cognitive load of the API (whats different between `filterWhile` than the combination of take and filter?) and also is a slippery slope as similar methods will end up being proposed.

**Comment by 7coder7** [comment]
@megawac yes I thought about that approach. The concern of traversing twice is what led me to this approach. Never looked it in through the perspective of load time though

**Comment by megawac** [comment]
I wasn't referring to actual script load/parse time, I meant that increasing the number of methods in a library increases how long it takes for someone to learn the API and the amount of concepts they need to keep track of

**Comment by jdalton** [comment]
Hi @7coder7!

This looks like [_.takeWhile](https://lodash.com/docs#takeWhile).

**Pull request closed without merging**
