### PR TITLE
Reword docs for _.tap and _.thru

### PR DESCRIPTION
**Pull request by jjt**
Recomend `_.thru` for altering/replacing intermediate values and `_.tap`
for triggering side-effects

### CODE REVIEW

**Comment by jdalton** [comment]
I like the `array.pop()` as it was. That example hits a use case devs ask about. The issue here is both allow mutating the value but really `tap` is for mutation and `thru` is for replacing.

**Comment by jdalton** [comment]
So the wording should reflect that.

**Comment by jdalton** [comment]
That `tap` is for mutation and `thru` is for replacing.

**Comment by jjt** [comment]
I don't think mutation of this sort is a good model to espouse in general. A chaining pipeline is easier to reason about if each step in the pipeline is a function that takes the current value and returns a new value to the next step.

`tap` for mutation and `thru` for replacement forces a conceptual divide between altering objects and primitive data types. There's no way to "mutate" a string using `_.tap`, you have to use `_.thru`.

It seems conceptually cleaner to me to recommend `_.thru` for any alteration of the intermediate value, and `_.tap` for side effects.

**Comment by jjt** [comment]
Another thing that bothers me about the `array.pop()` example is that there are better ways to do that (calling `.initial` directly on the chain). 

I think my intent behind this PR might be too opinionated toward FP ideas of pure functions and immutability (where practical in JS), which might not be suitable for recommendation in the docs.

**Comment by jdalton** [comment]
> I think my intent behind this PR might be too opinionated toward FP ideas of pure functions 

I'll do a compromise while still maintaining your commit cred.

**Comment by jjt** [comment]
Sure, that sounds reasonable to me. Pushed a new commit.

**Pull request merged**
