### PR TITLE
Fix prototype pollution vulnerability in zipObjectDeep (#4744)

### LINKED ISSUE #4744: Prototype pollution attack in zipObjectDeep
Affects: lodash 4.17.15 and below.

By including `__proto__` in the path of objects to zip, `Object.prototype` can be polluted.

```
_.zipObjectDeep(['a.b.__proto__.c'],[123])
console.log(c) // 123
```

This vulnerability was disclosed two days ago: https://hackerone.com/reports/712065

### PR DESCRIPTION
**Pull request by nickrobson**
Fixes #4744

### CODE REVIEW

**Comment by irfanfs** [comment]
Please approve and merge this asap

**Comment by Sytten** [comment]
Bump, this is important!

**Comment by Sytten** [comment]
Link to hackerone report: https://hackerone.com/reports/712065

**Comment by jdalton** [comment]
I'm aware of the issue and for me at least this is not a high priority issue. All disclosure and issues are not high priority and this one while technically an issue would require zipping objects based on user provided property matches. So I will address this but I'm not letting some report ruin my week or plans.

**Pull request closed without merging**
