### PR TITLE
Contributing.md - Link to enhancement issues

### PR DESCRIPTION
**Pull request by jfmengels**
Change the link from "closed issues" to "closed issues with enhancement label".

### CODE REVIEW

**Comment by demoneaux** [comment]
LGTM, merging. Thanks @jfmengels for all your contributions!

**Comment by jfmengels** [comment]
You're welcome ;)

**Comment by jdalton** [comment]
Imma pile on the thanks!
This project powered by volunteers. You both are a big help.

**Comment by jfmengels** [comment]
You're all welcome, having plenty of fun contributing ;)
And thank you all too for your work obiously!

**Pull request merged**
