### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by jdalton** [comment]
Hey Kevin! For a trivial PR like this you don't have to but have you considered signing [our CLA](http://dojofoundation.org/about/claForm)? It would open up further contributions in the future.

**Comment by kkirsche** [comment]
Signed

**Comment by jdalton** [comment]
Do you know if this affects [Duo](http://duojs.org/) support?

**Comment by kkirsche** [comment]
I've never heard of Duo before. My understanding though from the teams I've discussed this stuff with is that bower will be dying a slow and painful death honestly. So anything relying on Bower for this info is going to be screwed long term. Could be wrong, but that's just how I've understood the discussions

**Comment by jdalton** [comment]
From my quick glance Duo seems to gleam info from several places, bower being just 1 so it should be fine.

**Pull request merged**
