### PR TITLE
Non developer readme contribution

### PR DESCRIPTION
**Pull request by Gruximillian**
@jdalton 
I took the liberty of writing an introduction to the lodash library. I did so in consideration of new developers who just discovered this library and are trying to get some insight into what it is for. I attempted to make an introduction that even non-technical visitors can understand and get a general idea how lodash helps programmers in their work.  
Do you think that this can be helpful to inform lodash newcomers about the library?

### CODE REVIEW

**Comment by jdalton** [comment]
Can you flatten these commits to a single one. No need to re-open a PR you can just rebase in your branch and force push.

**Comment by jdalton** [comment]
Also have you signed [our cla](http://dojofoundation.org/about/cla).

**Comment by jdalton** [comment]
Closing in favor of #1954.

**Comment by Gruximillian** [comment]
I did a rebase and force push, but I see that you closed this pull request in favor of my fellow student's pull request.
Anyway, thank you for consideration.

**Pull request closed without merging**
