### PR TITLE
add support cyrillic (russian) for _.words

### PR DESCRIPTION
**Pull request by KhodeN**
ЁА-Я:  \u0401\u0410-\u042F
ёа-я: \u0451\u0430-\u044F

```
_.words('приветМир')
["привет", "Мир"]
```

### CODE REVIEW

**Comment by d10** [comment]
This seems like a simple enough change, but it would be unrealistic to support the many different languages out there. Also, other string functions like like `_.xyzCase` still would not written with these languages (I think).

**Comment by KhodeN** [comment]
It works fine for _.xyzCase:

```
console.log(_.words('приветМир'))
//  ["привет", "Мир"]
console.log(_.capitalize('приветМир'))
// ПриветМир
console.log(_.kebabCase('приветМир'))
// привет_мир
console.log(_.snakeCase('приветМир'))
// привет_мир
console.log(_.camelCase('Привет Мир'))
// приветМир
```
because all of this functions use the `reWords` regexp

**Comment by KhodeN** [comment]
Perhaps you are right, these functions will rarely be called with Cyrillic. 
On the other side, `reWords` supports for `latin-1`, not only English. For what?
I don't see much difficulty if you add support for Cyrillic characters also.

**Comment by jdalton** [comment]
We support a section of `latin-1` because we support deburring accents. For your case you can leverage `_.partialRight` or `_.partial` with placeholders and pass a [custom regexp](https://lodash.com/docs/#words):

```
var myWords = _.partial(_.words, _, myRegExp);
```

**Pull request closed without merging**
