### PR TITLE
Remove apply from memoized function call.

### PR DESCRIPTION
**Pull request by Mtnt**
It`s possible to call a func without changing its context.

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @Mtnt!

We still need the `this` binding of `apply`.

**Comment by Mtnt** [comment]
@jdalton why?

**Comment by Mtnt** [comment]
@jdalton could you explain why you still need `this` binding?

**Comment by Mtnt** [comment]
@jdalton ok, thanks, I just clarify for myself impossibility of double binding =)

**Pull request closed without merging**
