### PR TITLE
Feature/add average function

### PR DESCRIPTION
**Pull request by aguspina**

### CODE REVIEW

**Comment by jdalton** [comment]
Can you remove the `new dist` commit. It's distracting.

**Comment by jdalton** [comment]
Hi @aguspina!

Have you had a use case for `_.average` or are you just looking to complete a set of methods?

**Comment by aguspina** [comment]
Hi @jdalton !

I removed the dist commit.

Yesterday with my teammates we need to calculate some averages, and we agreed **lodash** should have it. Do you have any reason for not including it?

**Comment by jdalton** [comment]
> Do you have any reason for not including it?

No strong objection, it fits in well with `_.sum`. I'm just sanity checking to ensure a need came up.
Have you signed [our CLA](http://dojofoundation.org/about/claForm)?

**Comment by aguspina** [comment]
Just did it!

**Comment by jdalton** [comment]
Cool, can you rename this to `mean`.

**Comment by aguspina** [comment]
@jdalton Done!

**Comment by megawac** [comment]
Lgtm, though the description should probably read: computes the mean value of an array

**Comment by aguspina** [comment]
@megawac agree! Updated!

**Pull request merged**
