### PR TITLE
feat(last): add optional n elements parameter

### PR DESCRIPTION
**Pull request by danielbayley**
For example:
~~~ js
const array = [1,2,3,4]

_.last(array, { n: 2 }) // [3, 4]

_.last(array) // 4

[array].map(_.last) // [4]
~~~

### CODE REVIEW

**Comment by Trott** [comment]
Adding this feature seems like it will break use cases where `last()` is used as a callback to `Array.prototype.map()` and similar functions. 

It also seems like there's a footgun where `.last([1], 500)` returns `1` but `.last([1,2,3], 500)` returns an array.

**Comment by jdalton** [comment]
Our `last` method will be dropped for `Array.prototype.at` as in `array.at(-1)`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

**Comment by danielbayley** [comment]
> Our `last` method will be dropped for `Array.prototype.at` as in `array.at(-1)`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

@jdalton That’s nice, but it doesn’t give you a range as is the point of this PR…

**Comment by jdalton** [comment]
Are you thinking of https://lodash.com/docs/4.17.15#takeRight ?

**Pull request closed without merging**
