### PR TITLE
Link to Changelog and other wiki pages from main README. Fixes #875

### LINKED ISSUE #875: wish: document breaking changes in 3.0.0
As a semantic version, 3.0.0 implies some sort of breaking change compared to 2.4 to 2.2. 

While a full ChangeLog would be nice, at least documenting compatibility issues from 2.2 to 2.4 and 2.4 to 3.0 would be helpful for those considering upgrading.

Thanks for lodash-- I use it nearly daily!

### PR DESCRIPTION
**Pull request by markstos**

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks!

**Comment by dwelle** [comment]
@jdalton It seems this commit has been reverted at some point. Would you consider reintroducing the link (to at least the _changelog_) into readme? Putting it under wiki is pretty uncommon and new users may not even find it. Useful shortcut for others, too.

**Comment by jdalton** [comment]
It's covered by our wiki link. I don't want to enumerable all the things in the wiki and rather link to the wiki where it's a reasonable assumption that's where things like a changelog are located.

**Comment by markstos** [comment]
Having a top-level Changelog.md or History.md is highly standard. If a
project doesn't have one,  I presume they likely don't have a Changelog.

For the Lodash project, not seeing a Changelog.md, I would next try the
"Docs" link, since the Changelog is a kind of documentation. Not finding it
there, I would give up.

One solution is create to a mostly empty and static Changelog.md that
simply contains a paragraph that links to the Changelog of the wiki.

**Comment by jdalton** [comment]
Cool would you like to create a PR to add a `CHANGELOG` file with a link to the wiki changelog?

**Pull request merged**
