### PR TITLE
tweak _.clone/_.cloneDeep docs

### PR DESCRIPTION
**Pull request by dwelle**
Ad https://github.com/lodash/lodash/issues/4212.

Sorry for the delay. Also not sure whether to address the deprecated structured clone algo, so I just added note about copying the prototype.

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @dwelle!

The sentence "Prototype is copied." feels kind of shoehorned in. Can you try to make it more conversational.

**Comment by dwelle** [comment]
@jdalton absolutely, but I have no clue what wording to choose. "Original prototype reference is kept" perhaps?

**Comment by jdalton** [comment]
You could say something like `"Object inheritance is preserved."

**Comment by dwelle** [comment]
Sounds good. Amended. Thanks for assistance.

**Comment by jdalton** [comment]
Thank you @dwelle!

**Pull request merged**
