### PR TITLE
Update links in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dwesty17**
Fixed the js foundation links

### CODE REVIEW

**Comment by falsyvalues** [comment]
Thank You @dwesty17!

**Comment by bnjmnt4n** [comment]
Ironically the CLA bot didn’t catch this PR - not sure if that’s a bug…

**Comment by falsyvalues** [comment]
@bnjmnt4n yeah 😄

**Comment by bnjmnt4n** [comment]
Not sure if that means that this PR shouldn’t have been merged since I'm no sure if the CLA has been signed - however, my knowledge of licensing is at best minimal, maybe someone who is more knowledgeable can chime in.

**Pull request merged**
