### PR TITLE
Some issues with lodash-fp.

### PR DESCRIPTION
**Pull request by d10**
The methods in `keyMap` (curryN, getOr, sampleSize) don't seem to work properly too, probably some bind wrapper thing going wrong?

### CODE REVIEW

**Comment by jdalton** [comment]
No worries on the `sampleSize`, that's a method we have now so it probably just needs proper mapping.

**Comment by d10** [comment]
Ah, didn't notice `sampleSize` was split out.

**Comment by jdalton** [comment]
The curry methods were fine. Lodash curry methods can accept more than the specified arity. The arity signals when the wrapper should invoke `func`.

**Comment by d10** [comment]
My bad, I've always thought it limits the number of arguments pased into the function. I don't think the docs are very clear on that.

**Comment by jdalton** [comment]
I'll adjust the docs.

**Pull request merged**
