### PR TITLE
Add `_.isPrime` function for numbers

### PR DESCRIPTION
**Pull request by J3remyD**
Adding isPrime function !!

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks for the PR @J3remyD!

I'd like to hold off on this until there's more user demand for it.

**Comment by J3remyD** [comment]
oh ... Ok, since github doesn't allow me to chat except for comments, can you give me some user demand feature I could contribute for if I want to contribute ?

**Comment by jdalton** [comment]
User demand is measured by requests or :+1:'s.

**Comment by J3remyD** [comment]
I'm sure of that, I just wanted to know if there's an official link to check those or it's not public ??

**Comment by jdalton** [comment]
No official way, it's usually tracked on the issue/request in question.

**Comment by J3remyD** [comment]
OK i'll check it thanks

**Comment by jdalton** [comment]
Moved to #2370.

**Pull request closed without merging**
