### PR TITLE
Bump lodash-es to v4.17.20.

### PR DESCRIPTION
**Pull request by opichals**
Steps to reproduce

* Update the lodash version in lodash-cli tool
  ```sh
  cd ../lodash-cli
  vi package.json
  npm install
  cd -
  ```
* Run the lodash-cli tool with the proper exports flag
  ```sh
  node ../lodash-cli/bin/lodash modularize exports="es" -o ./
  ```

After merging this should be hopefully ready for `npm publish` in the `es` branch and tagged `4.17.20-es`.

### CODE REVIEW

**Comment by nerdkid93** [comment]
This is a near duplicate of https://github.com/lodash/lodash/pull/4947

**Comment by opichals** [comment]
@nerdkid93 Ah, sorry, just noticed. I created it based on this https://github.com/lodash/lodash/issues/4879#issuecomment-722563017 made by the npmjs.org registry collaborator...

**Comment by opichals** [comment]
Related https://github.com/lodash-archive/lodash-cli/pull/143

**Comment by opichals** [comment]
@bnjmnt4n Since it looks like you did the `npm publish` for `lodash@4.17.20`. Could you have a look at this?

**Comment by bnjmnt4n** [comment]
Thanks for the PR! I had to re-generate the build myself, but really appreciate your help here. Closing!

**Pull request closed without merging**
