### PR TITLE
Added _.chunkBy

### PR DESCRIPTION
**Pull request by tbroadley**
As requested in #1379, #1700, #1962.

I was also thinking about generalizing `_.chunk` to take an iteratee as an argument. Honestly I think either way would work fine.

### CODE REVIEW

**Comment by tbroadley** [comment]
I'm pretty sure that I have signed the CLA with the same name and email as are in my git config.

**Comment by jdalton** [comment]
Hi @tbroadley!

If you click the "[Details](http://contribute.jquery.org/CLA/status/?owner=lodash&repo=lodash&sha=cf11ba3dca84c3221a9aecd444357428845aadd0)" link on the failing jQuery Foundation CLA check you'll see:
> tbroadley <buriedunderbooks@hotmail.com>: Name on signature (Thomas Broadley) doesn't match name on commit.

The details page also has instructions on how to resolve it.

**Comment by tbroadley** [comment]
Thanks @jdalton! I will keep trying to get my config to match my CLA signature.

**Comment by tbroadley** [comment]
There we go!

**Comment by jdalton** [comment]
Thanks @tbroadley!

I'd like to hold off until user demand for #1379 is a bit higher.

**Comment by jdalton** [comment]
When it is though we'll use this PR as the base implementation.

**Comment by tbroadley** [comment]
Sounds good. Thanks for taking a look!

**Comment by TimoStolz** [comment]
+1

**Comment by elmigranto** [comment]
First of all, ❤️ to everyone who have contributed. `lodash` is real joy to use, thank you!

<hr />

Was about to ask for this a tenth time it seems, there are a bunch of votes on original issue and this PR, seems popular and definetly a useful thing. Any chance this can be reconsidered, @jdalton?

**Pull request closed without merging**
