### PR TITLE
Use parentheses around arrow function argument having a body with cur…

### PR DESCRIPTION
**Pull request by falsyvalues**
It's a style matter, but reasonable to use parentheses when you use function body.
So use `var => fn(var)` or `(var) => {  fn(var) }`, what do you think?

### CODE REVIEW

**Comment by RusinovAnton** [comment]
FYI your both examples have different outcome
`var => fn(var)` - returns result of `fn(var)`
`(var) => { fn(var) }` - doesn't return anything, just calling `fn(var)`
These two are equal
`var => fn(var)` or `(var) => { return fn(var) }`

**Comment by falsyvalues** [comment]
I know outcome, it was just example of coding style :+1:

**Comment by jdalton** [comment]
Hi @falsyvalues!

I'm OK with keeping functions with single params without parens.

**Comment by falsyvalues** [comment]
Sure thing :+1:

**Pull request closed without merging**
